### PR TITLE
Emotions & Minecraft Terms

### PR DESCRIPTION
**Pull request by afterlifes**
https://www.berkeleywellbeing.com/list-of-emotions.html
https://www.idtech.com/blog/minecraft-glossary-of-terms-and-words-to-know

### CODE REVIEW

**Comment by 84** [comment]
&gt;schadenfreude  
not english word

**Comment by 84** [comment]
nvm it can be used in english but still wouldnt really consider og

**Comment by RisingChops** [comment]
> nvm it can be used in english but still wouldnt really consider og

removed it

**Review by orsou — APPROVED** [review]
Looks good!

**Comment by Dqnns** [comment]
ready to merge

**Comment by bribes** [comment]
Merge this

**Comment by Dqnns** [comment]
Ready to merge!

**Comment by LabyStudio** [comment]
We want to collect names that are actually considered as OG and have a high value and not just every existing English word.
I suggest to get rid of long, unusual and complicated words ^^

**Comment by RisingChops** [comment]
> We want to collect names that are actually considered as OG and have a high value and not just every existing English word. I suggest to get rid of long, unusual and complicated words ^^

Sorry about that, I looked at the existing list and some of them are very low tier semis so I just assumed it included them. Fixed it!

**Comment by Dqnns** [comment]
removed awe for you since its just an unnecessary word.

**Comment by 84** [comment]
Awe goes kinda hard not gonna front

**Comment by bribes** [comment]
Many of these I'd consider semi imo. Like frustrated can just be frustrate and stuff like grouchiness can just be grouchy.

**Comment by fez6** [comment]
> Many of these I'd consider semi imo. Like frustrated can just be frustrate and stuff like grouchiness can just be grouchy.

This is kind of a hard subject since I for example would agree with the later example and say "grouchy" would be more OG, but I would consider "frustrated" more OG than "frustrate".

**Comment by bribes** [comment]
> > Many of these I'd consider semi imo. Like frustrated can just be frustrate and stuff like grouchiness can just be grouchy.
> 
> This is kind of a hard subject since I for example would agree with the later example and say "grouchy" would be more OG, but I would consider "frustrated" more OG than "frustrate".

Ig I agree. 👍

**Comment by Dqnns** [comment]
The list needs some work done. There are many semis in there...

**Pull request closed without merging**
