### PR TITLE
Added "categorization" to nouns.txt

### PR DESCRIPTION
**Pull request by Minecrafter0101**
Commonly used word.
"Categorization" is the action or process of placing into classes or groups.

https://www.vocabulary.com/dictionary/categorization

https://www.oxfordlearnersdictionaries.com/definition/english/categorization

https://dictionary.cambridge.org/dictionary/english/categorization

https://www.oed.com/dictionary/categorization_n?tl=true

https://www.collinsdictionary.com/dictionary/english/categorization

https://dictionary.apa.org/categorization

### CODE REVIEW

**Comment by ignUffizi** [comment]
Its definetly a common word and semi og if not og.

**Comment by Minecrafter0101** [comment]
> I think this is kinda semi

Definitely is a commonly used word, and a decent semi.

**Comment by Dqnns** [comment]
Semi

**Comment by Minecrafter0101** [comment]
Alright

**Pull request closed without merging**
