### PR TITLE
Added "Hoar"

### PR DESCRIPTION
**Pull request by GaryxHarlow**
**Hoar**: This surname is derived from a nickname. 'the hoar,' i.e. the white, the greyish white; probably from complexion of the hair. https://forebears.io/surnames/hoar

**FunkyFurby**: Very popular toy very well known the most popular furby toy. https://official-furby.fandom.com/wiki/Funky_Furby

### CODE REVIEW

**Comment by Dqnns** [comment]
Why did you create a `src/NamesAdded.txt` ?

**Comment by GaryxHarlow** [comment]
> Why did you create a `src/NamesAdded.txt` ?

idk so it's easier to read what names I added. I can delete if needed.

**Comment by Dqnns** [comment]
delete funkyfurby, not an "OG" at all...

**Comment by GaryxHarlow** [comment]
Done

**Comment by Dqnns** [comment]
Wouldn't consider this "OG".

**Pull request closed without merging**
