### PR TITLE
Add Name "Haul" to the list it is another word for "drag" or "pull"

### PR DESCRIPTION
**Pull request by g59magnus**
Add Name "Haul" to the list it is another word for "drag" or "pull"

### CODE REVIEW

**Comment by bribes** [comment]
I approve which doesn't really mean anything but yeah I think it should be added.

**Comment by 84** [comment]
I agree

**Comment by bribes** [comment]
You did this pull request completely wrong though lmao

**Comment by Dqnns** [comment]
You need to fix the PR so I can merge it.

**Comment by g59magnus** [comment]
> You need to fix the PR so I can merge it.

I have no clue how to fix it, i dont work with github that much, can you please say me what i have to do?

**Comment by bribes** [comment]
> > You need to fix the PR so I can merge it.
> 
> I have no clue how to fix it, i dont work with github that much, can you please say me what i have to do?

I will make one for you its fine.

**Comment by g59magnus** [comment]
> > > You need to fix the PR so I can merge it.
> > 
> > 
> > I have no clue how to fix it, i dont work with github that much, can you please say me what i have to do?
> 
> I will make one for you its fine.

Thank you, so i only have to create a new PR?

**Comment by Dqnns** [comment]
> > > > You need to fix the PR so I can merge it.
> > > 
> > > 
> > > I have no clue how to fix it, i dont work with github that much, can you please say me what i have to do?
> > 
> > 
> > I will make one for you its fine.
> 
> Thank you, so i only have to create a new PR?

Yes please.

**Pull request closed without merging**
