### PR TITLE
Added and remove some words

### PR DESCRIPTION
**Pull request by bribes**
Added:
- Sentimental
- Blurt
- Connor
- Conner
- Diplomat
- Diplomacy
- Diplomatic
- Emo
- Ballroom
- Psycho
- Psychopath
- Exodus
- Fume
- Influx
- Twerk
- Duel
- Carnage
- Impale
- Condone
- Condense
- Lapse
- Slender
- Slander
- Crumble
- Crumb
- Enrage (Might be good to add to the Emotions & Minecraft Terms PR if that gets pushed)
- Grumpy (Already added in Emotions & Minecraft Terms PR so may be removed)

Removed (removed these because thought they were random, I could be wrong):
- msgid
- msgstr
- acdbentity

Feel free to give feedback in comments and tell me what to add and remove.

Edit: Turns out I didn't put Sentimental in the commit history but it is included with the "Add Diplomatic" commit.

Edit 2: Might make another PR for a abbreviations folder and file with stuff like wtf, lmao, etc.

Edit 3: Added a adjectives.txt file for the adjectives I added.

### CODE REVIEW

**Comment by F0xyMC** [comment]
Agreed 100%! Add this!

**Comment by britisk** [comment]
Maybe add Enragement and Usabilities aswell?

**Comment by bribes** [comment]
I only put the the ones that Google considered as “OG”.

**Comment by condone** [comment]
enraged would be semi imo

**Comment by bribes** [comment]
> enraged would be semi imo

I placed Enraged in google.txt because Google considers it it's own word.

**Review by orsou — APPROVED** [review]
Looks good! 👍

**Comment by F0xyMC** [comment]
merge?

**Comment by bribes** [comment]
> > > enraged would be semi imo
> > 
> > 
> > I placed Enraged in google.txt because Google considers it it's own word. But if anyone else agrees I can remove.
> 
> It is semi

Well if thats true i'd have to remove like a 100 words from google.txt we can do that in another PR.

**Comment by F0xyMC** [comment]
> > > > enraged would be semi imo
> > > 
> > > 
> > > I placed Enraged in google.txt because Google considers it it's own word. But if anyone else agrees I can remove.
> > 
> > 
> > It is semi
> 
> Well if thats true i'd have to remove like a 100 words from google.txt we can do that in another PR.

Does anyone second this?

**Comment by F0xyMC** [comment]
If nobody has an issue with it then someone who can should merge with the master branch

**Comment by Dqnns** [comment]
Look good, I still don't agree with **Landon**, I don't know what that means...

**Comment by LabyStudio** [comment]
I'm not really a fan of adding new words to the google category. (Because it is a source)
You can remove words from this list or split it up in different categories if you want to.

Maybe you should create a category for adjectives instead?

**Comment by bribes** [comment]
> I'm not really a fan of adding new words to the google category. (Because it is a source)
> You can remove words from this list or split it up in different categories if you want to.
> 
> Maybe you should create a category for adjectives instead?

Sure thing!

**Comment by bribes** [comment]
> Look good, I still don't agree with **Landon**, I don't know what that means...

Landon is a common name

**Comment by Dqnns** [comment]
> > Look good, I still don't agree with **Landon**, I don't know what that means...
> 
> Landon is a common name

Still disagreeing, just divided opinions

**Comment by bribes** [comment]
If I will remove Landon and I’ll create a adjectives.txt

**Comment by bribes** [comment]
> > I guess I will remove Landon and I’ll create a adjectives.txt
> 
> Would be amazing ^^

How would I extract all adjectives from google.txt though?

**Comment by Dqnns** [comment]
create a adjectives.txt

and just copy paste them into there.

**Comment by bribes** [comment]
> create a adjectives.txt
> 
> and just copy paste them into there.

Done

**Comment by bribes** [comment]
oops

**Comment by F0xyMC** [comment]
bruh

**Pull request merged**
