### PR TITLE
Update adjectives.txt

### PR DESCRIPTION
**Pull request by Garganacl**
outrageous

### CODE REVIEW

**Comment by Dqnns** [comment]
run the `cleanup.py` script!

**Comment by Garganacl** [comment]
What

**Comment by Garganacl** [comment]
I ran it and nothing happened?

**Comment by Garganacl** [comment]
Idk if you can help or not im just trying to get it on the og badge list as it means something different then 'outrage' and can only be used in different contexts

https://www.merriam-webster.com/dictionary/outrage
https://www.merriam-webster.com/dictionary/outrageous

**Pull request closed without merging**
