### PR TITLE
Raichu + MP15

### PR DESCRIPTION
**Pull request by t84**
https://bulbapedia.bulbagarden.net/wiki/Raichu_(Pok%C3%A9mon)

https://en.wikipedia.org/wiki/Smith_%26_Wesson_M%26P15

### CODE REVIEW

**Comment by ignBruneian** [comment]
I dont think that MP15 is og. And Raichu is a Pokemon, but idk if you consider it OG, maybe its a cultural OG.

**Comment by t84** [comment]
> I dont think that MP15 is og. And Raichu is a Pokemon, but idk if you consider it OG, maybe its a cultural OG. 

I mean alot of the things on the list aren't "OG" Just as long as they have multiple sources it should be considered one for laby.

**Comment by ignBruneian** [comment]
Yeah true and according to the guy named phobia, any pokemon name counts as a cultural OG.

**Comment by Dqnns** [comment]
"OG" enough, thanks!

**Pull request merged**
