### PR TITLE
Add Serkan

### PR DESCRIPTION
**Pull request by yariquv1**
Serkan a famous turkish Name 
https://de.wikipedia.org/wiki/Serkan

### CODE REVIEW

**Comment by Downlands** [comment]
Add: "Mondo"

Definition: very large in amount [Source](https://www.merriam-webster.com/dictionary/mondo)

**Comment by Dqnns** [comment]
Serkan isn't really "OG"

> Add: "Mondo"
> 
> Definition: very large in amount [Source](https://www.merriam-webster.com/dictionary/mondo)

Mondo isn't a Name nor a "OG" Name.

**Comment by JuNukiii** [comment]
Nice Name

**Comment by Jordan1Dior** [comment]
best og name i know man this is crazy <3

**Comment by Strafgesetz** [comment]
Sehr guter OG Name <3

**Comment by saiwtwitch** [comment]
nice name , most known name in turkey and germany

**Comment by saiwtwitch** [comment]
> Serkan isn't really "OG"
> 
> > Add: "Mondo"
> > Definition: very large in amount [Source](https://www.merriam-webster.com/dictionary/mondo)
> 
> Mondo isn't a Name nor a "OG" Name.

dude its OG name how its possible to not be OG

**Comment by 84** [comment]
Not OG

**Comment by Dqnns** [comment]
convinced

**Pull request merged**
