### PR TITLE
add Klarissa 

### PR DESCRIPTION
**Pull request by dripluan**
I think "Klarissa" deserves an OG badge
https://forebears.io/x/forenames/klarissa
https://www.thebump.com/b/klarissa-baby-name#chart

### CODE REVIEW

**Comment by DavidRodriguez2001** [comment]
that's definitely an OG name!

**Comment by MaxKalkbrenner** [comment]
Klarissa is actually known everywhere, very good name.

**Comment by pumper78** [comment]
should be added for sure

**Comment by Dqnns** [comment]
Semi

**Pull request closed without merging**
