### PR TITLE
Create foods.txt

### PR DESCRIPTION
**Pull request by schnappi21**
Added:
› Bagel 🥯
› Baguette 🥖
› Biscuits
› Broth
› Burrito 🌯
› Cereal
› Cheeseburger 🍔
› Croissant 🥐
› Cupcake 🧁
› Curry 🍛
› Donut 🍩
› Doughnut 🍩
› Dumpling 🥟
› Falafel 🧆
› Flatbread
› Fries 🍟
› Hamburger 🍔
› HotDog 🌭
› Kebab 🥙
› Muffin
› Nacho
› Noodle 🍜
› Omelet
› Pancake 🥞
› Popcorn 🍿
› Pretzel 🥨
› Pudding 🍮
› Ramen 🍜
› Sausage
› Spaghetti 🍝
› Taco 🌮
› Takeout 🥡
› Toast
› Waffle 🧇
› Yogurt

[Later added foods.](https://github.com/LabyMod/og-names/pull/59/commits/213df7006bdf037c00317284fdc51ff60da7be4c)

### CODE REVIEW

**Comment by bribes** [comment]
foods.txt is probably a better name that fits with the other files.

**Comment by fez6** [comment]
> foods.txt is probably a better name that fits with the other files.

You're right, the countable plural would be more fitting here.

> Also no pizza or cookie...

I left out all the foods that were already listed in other files. (1) 

> You'll also have to remove the foods from the other files.

I will probably remove all the foods from the other files and combine them into this file, fixing (1).

**Comment by Dqnns** [comment]
Maybe merge everything together?

**Comment by fez6** [comment]
> Reference in

You mean #50, #58 and #59?

**Comment by 84** [comment]
Frie isn't a word. Should be Fry if Fry doesn't exist already.

**Comment by bribes** [comment]
> Frie isn't a word. Should be Fry if Fry doesn't exist already.

Fries is the plural of Fry you'd say I ate Fries not I ate Fry.

**Comment by fez6** [comment]
> Frie isn't a word. Should be Fry if Fry doesn't exist already.

You're right, I will change it later today.

**Comment by fez6** [comment]
https://github.com/LabyMod/og-names/pull/59#issuecomment-1105107092 @Dqnns?

**Comment by Dqnns** [comment]
> [#59 (comment)](https://github.com/LabyMod/og-names/pull/59#issuecomment-1105107092) @Dqnns?

No, I didn't mean that.

My suggestions was to merge every food item together so we have a food.txt where we put in all edibles.

**Comment by fez6** [comment]
> My suggestions was to merge every food item together so we have a food.txt where we put in all edibles.

You mean removing fruits.txt and vegetables.txt and putting them in here, could work but I'm not sure if the file would be too cluttered then. Anyways feel free to edit this pull request to your needs.

**Pull request closed without merging**
