### PR TITLE
Fantasize + Vandalize (edit to google.txt)

### PR DESCRIPTION
**Pull request by Vandalize1231**
Adding Fantasize + Vandalize (OG Names, and real words)

### CODE REVIEW

**Comment by Dqnns** [comment]
Hey,

please add other OG names to the list not just your own...

**Comment by bribes** [comment]
You should've added these to verbs.txt not google.txt because google.txt is for popular used words so verbs.txt is a better place.

**Comment by bribes** [comment]
Why'd you delete google.txt??

**Comment by Vandalize1231** [comment]
> Why'd you delete google.txt??
My bad, dont know how to do pulls very well. Was trying to delete my changes and add to verbs.txt

**Comment by bribes** [comment]
> > Why'd you delete google.txt??
> > My bad, dont know how to do pulls very well. Was trying to delete my changes and add to verbs.txt

It's fine ig just reset lol, you can just delete the fork make a new one then follow the steps again except for the verbs.txt file, not the google.txt.

**Pull request closed without merging**
