### PR TITLE
Russia

### PR DESCRIPTION
**Pull request by Dosenpisser**

### CODE REVIEW

**Comment by Dqnns** [comment]
This is just a copy paste thing. You have to look at the names and cosider what is "OG" and what is not "OG"...

You need to overwork this...

**Review by orsou — CHANGES_REQUESTED** [review]
Not every name on a "*[insert country name here]* Name List" you can find on the internet is considered OG.
I agree with @Dqnns you should definitly rework this.

**Comment by LabyStudio** [comment]
> Not every name on a "_[insert country name here]_ Name List" you can find on the internet is considered OG. I agree with @Dqnns you should definitly rework this.

How about #9?

**Comment by orsou** [comment]
> How about #9?

After [this aspect](https://github.com/LabyMod/og-names/pull/9#pullrequestreview-841906714) was fixed by DanniDev1 I would say most of the names in the list are OG, but there are still a good amount of names that probably 99% of the OG-Community & Minecraft-Community would not count as OG names. However if the laby.net team considers every real name as OG it is a good list.

**Pull request merged**
