### PR TITLE
Create abbreviations.txt

### PR DESCRIPTION
**Pull request by fez6**
Added:
› 4AO - For adults only
› AFK - Away from keyboard
› AKA - Also known as
› ASAP - As soon as possible
› BAE - Before anyone else
› BFF - Best friend forever
› BRB - Be right back
› BTW - By the way
› BUMP - Bring up my post
› CTR - Click-through rate
› DIY - Do it yourself
› ETC - Et cetera
› FAQ - Frequently asked questions
› FYI - For your information
~› G2G - Got to go~
› GTG - Got to go
› HMU - Hit me up
› IDC - I don't care
› IDK - I don't know
› ILY - I love you
› IMO - In my opinion
› J4F - Just for fun
› KISS - Keep it simple stupid
› LMAO - Laughing my ass off
› LMFAO - Laughing my f\*\*\*ing ass off
› LMK - Let me know
› MSG - Message
› NSFW - Not safe for work
› NVM - Nevermind
› OMW - On my way
› PPL - People
› POV - Point of view
› QNA - Questions and answeres
› ROFL - Rolling on floor laughing
› RUOK - Are you okay
› SOS - Save our ship
› SMS - Short message service
› STFU - Shut the f\*\*k up
› TBH - To be honest
› TTYL - Talk to you later
› UUID - Universally unique identifier
› VIP - Very important person
› WTF - What the f\*\*k
› XMAS - Christmas
› Y2K - The year 2000
› ZZZ - Sleeping noise

[Later added abbreviations.](https://github.com/LabyMod/og-names/pull/58/commits/208c2bd124566258d50028f927006f5175073577)

### CODE REVIEW

**Comment by fez6** [comment]
I'm not sure if every abbreviation listed here is considered OG so please let me know which ones to remove or add.

**Comment by bribes** [comment]
I don't this these are common: 4AO, RUOK, J4F

Also G2G is GTG

The rest look good!

**Comment by fez6** [comment]
> I don't this these are common: 4AO, RUOK, and J4F. Not 100% sure though.

I'm not really sure about them either let's see what the other contributors think about this first, but I would not mind removing them.

> Also G2G is GTG

Fixed in [this commit.](https://github.com/LabyMod/og-names/pull/58/commits/33a2771db38eaeb82b29a4c25b0d76dfcf6d619f)

**Comment by Dqnns** [comment]
Looks very good. ^^

**Pull request merged**
