### PR TITLE
Added "Slenk"

### PR DESCRIPTION
**Pull request by SlenkyDev**
source: https://forebears.io/search?q=Slenk&meaning=genealogy-names-surnames

### CODE REVIEW

**Comment by condone** [comment]
very obscure name, don't think this would get approved tbh

**Comment by SlenkyDev** [comment]
I hope it does lol
but I wouldn't be mad either

------- Original Message -------

**Comment by Dqnns** [comment]
Never met a Slenk - wouldn't consider this a "OG" either.

**Comment by Dqnns** [comment]
Closing this because it isn't an "OG"

**Pull request closed without merging**
