### PR TITLE
Add "reking" to og names!

### PR DESCRIPTION
**Pull request by rekimg**
This word is an English word going back to the times of monarchy.

https://www.wordnik.com/words/reking#:~:text=To%20make%20king%20again%3B%20raise%20to%20the%20monarchy%20anew

https://forebears.io/forenames?q=reking

### CODE REVIEW

**Comment by Dqnns** [comment]
run `cleanup.py`

**Comment by rekimg** [comment]
> run `cleanup.py`

How?

**Comment by Dqnns** [comment]
> > run `cleanup.py`
> 
> How?

If you can't run` cleanup.py`, please put the name in alphabetical order.

**Comment by rekimg** [comment]
> 

> > > run `cleanup.py`
> > 
> > 
> > How?
> 
> If you can't run` cleanup.py`, please put the name in alphabetical order.

I did

**Comment by rekimg** [comment]
Never mind the newest commit has the correct placement.

**Pull request merged**
