### PR TITLE
Update sports.txt

### PR DESCRIPTION
**Pull request by fez6**
Added:
› Baseball
› Bobsleigh
› ~Canoeing~
› Cricket
› Crossfit
› Dancing
› ~Esports~
› Fencing
› Fishing
› Frisbee
› Golf
› Gymnastics
› Lifting
› Poker
› ~Powerlifting~
› Swimming
› Tennis
› Wrestling

### CODE REVIEW

**Comment by 84** [comment]
Canoeing is not OG.

**Comment by fez6** [comment]
> Canoeing is not OG.

True.

**Comment by Dqnns** [comment]
@fez6 ?

**Comment by fez6** [comment]
> @fez6 ?

Yes?

**Comment by 84** [comment]
Powerlifting is semi also

**Comment by fez6** [comment]
> Powerlifting is semi also

Removed.

**Comment by fez6** [comment]
> > @fez6 ?
> 
> Yes?

**Comment by fez6** [comment]
> > @fez6 ?
> 
> Yes?

@Dqnns ?

**Comment by Dqnns** [comment]
> Powerlifting is semi also

Esports too

**Comment by fez6** [comment]
> > Powerlifting is semi also
> 
> Esports too

@Dqnns done.

**Pull request merged**
