### PR TITLE
Updated nouns.txt

### PR DESCRIPTION
**Pull request by h4rmy**
Added guarantor

### CODE REVIEW

**Comment by bribes** [comment]
I don't think this is considered "OG".

**Comment by 84** [comment]
Not OG

**Comment by h4rmy** [comment]
why not? it has a meaning of middleman or someone who gives guaranties, in my opinion it is a og name

**Comment by bribes** [comment]
Yeah, I don't think this is considered "OG".

**Comment by Dqnns** [comment]
> Yeah, I don't think this is considered "OG".

Yup

**Pull request closed without merging**
